CREATE TABLE RECINTOS (
    COD_RECINTO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL DEFAULT 'NoName',
    DIRECCION VARCHAR(100) NOT NULL DEFAULT 'NoAddress',
    TELEFONO INT NOT NULL DEFAULT 0,
    HORAENTRADA TIME NOT NULL DEFAULT '01:00:00',
    HORACERRAR TIME NOT NULL DEFAULT '02:00:00'
);

-- Crear Tabla Zonas_Recintos
CREATE TABLE ZONAS_RECINTOS (
    COD_ZONA INT PRIMARY KEY IDENTITY(1,1),
    COD_RECINTO INT NOT NULL,
    ZONA VARCHAR(50) NOT NULL DEFAULT 'NoZone',
    CAPACIDAD INT NOT NULL DEFAULT 0,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO)
);

-- Crear Tabla Asientos
CREATE TABLE ASIENTOS (
    COD_ASIENTO INT PRIMARY KEY IDENTITY(1,1),
    COD_RECINTO INT NOT NULL,
    ZONA VARCHAR(50) NOT NULL DEFAULT 'NoZone',
    FILA VARCHAR(50) NOT NULL DEFAULT 'NoRow',
    NUMERO INT NOT NULL DEFAULT 0,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO)
);

-- Crear Tabla Espectaculos
CREATE TABLE ESPECTACULOS (
    COD_ESPECTACULO INT PRIMARY KEY IDENTITY(1,1),
    NOMBRE VARCHAR(50) NOT NULL DEFAULT 'NoName',
    TIPO VARCHAR(50) NOT NULL DEFAULT 'NoType',
    FECHA_INICIAL DATE NOT NULL DEFAULT '2000-01-01',
    FECHA_FINAL DATE NOT NULL DEFAULT '2000-01-01',
    INTERPRETE VARCHAR(100) NOT NULL DEFAULT 'NoPerformer',
    COD_RECINTO INT NOT NULL,
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO)
);

-- Crear Tabla Representaciones
CREATE TABLE REPRESENTACIONES (
    COD_REPRESENTACION INT PRIMARY KEY IDENTITY(1,1),
    COD_ESPECTACULO INT NOT NULL,
    FECHA DATE NOT NULL DEFAULT '2000-01-01',
    HORA TIME NOT NULL DEFAULT '01:00:00',
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO)
);

-- Crear Tabla Entradas
CREATE TABLE ENTRADAS (
    COD_ENTRADA INT PRIMARY KEY IDENTITY(1,1),
    COD_ESPECTACULO INT NOT NULL,
    FECHA DATE NOT NULL DEFAULT '2000-01-01',
    HORA TIME NOT NULL DEFAULT '01:00:00',
    COD_RECINTO INT NOT NULL,
    FILA VARCHAR(50) NOT NULL DEFAULT 'NoRow',
    NUMERO INT NOT NULL DEFAULT 0,
    ZONA VARCHAR(50) NOT NULL DEFAULT 'NoZone',
    DNI_CLIENTE INT NOT NULL DEFAULT 0,
    FOREIGN KEY (COD_ESPECTACULO) REFERENCES ESPECTACULOS(COD_ESPECTACULO),
    FOREIGN KEY (COD_RECINTO) REFERENCES RECINTOS(COD_RECINTO)
);

-- Crear Tabla Espectadores
CREATE TABLE ESPECTADORES (
    DNI_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL DEFAULT 'NoName',
    APELLIDO VARCHAR(50) NOT NULL DEFAULT 'NoLastName',
    CALLE VARCHAR(50) NOT NULL DEFAULT 'NoStreet',
    NUMERO INT NOT NULL DEFAULT 0,
    TELEFONO INT NOT NULL DEFAULT 0,
    CIUDAD VARCHAR(50),
    NTARJETA INT NOT NULL DEFAULT 0
);