-- Crear Tabla LOCALIDAD Primero, para teniendo nuestra primera primary key en COD_LOCALIDAD
CREATE TABLE LOCALIDAD (COD_LOCALIDAD INT PRIMARY KEY AUTO_INCREMENT, NOMBRE VARCHAR(100) NOT NULL DEFAULT 'NoName');
-- Crear Tabla PUB que usara COD_LOCALIDAD como llave foranea
CREATE TABLE PUB (COD_PUB VARCHAR(100) PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL DEFAULT 'NoName', LICENCIA_FISCAL VARCHAR(100) NOT NULL DEFAULT 'NoLicence', 
CALLE VARCHAR(100) NOT NULL DEFAULT 'NoStreet', NUMERO INT NOT NULL DEFAULT '0', NROAPTO INT NOT NULL DEFAULT '0', FECHA_APERTURA DATE NOT NULL DEFAULT '2000-01-01',
HOR1 TIME NOT NULL DEFAULT '01:00:00', HOR2 TIME NOT NULL DEFAULT '02:00:00', COD_LOCALIDAD INT, FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD));
-- Crear la tabla TITULAR que usara COD_PUB como llave foranea 
CREATE TABLE TITULAR (DNI_TITULAR VARCHAR(8) PRIMARY KEY DEFAULT '00000000', NOMBRE VARCHAR(100) NOT NULL DEFAULT 'NoName', CALLE VARCHAR(100) NOT NULL DEFAULT 'NoStreet', 
NUMERO INT NOT NULL DEFAULT '0', NROAPTO INT NOT NULL DEFAULT '0', COD_PUB VARCHAR(100), FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB));
-- Crear la tabla EMPLEADO
 CREATE TABLE EMPLEADO (DNI_EMPLEADO VARCHAR(8) PRIMARY KEY DEFAULT '00000000', NOMBRE VARCHAR(100) NOT NULL DEFAULT 'NoName', CALLE VARCHAR(100) NOT NULL DEFAULT 'NoStreet', 
NUMERO INT NOT NULL DEFAULT '0', NROAPTO INT NOT NULL DEFAULT '0');
-- Crear la tabla EXISTENCIAS que usara como llave foranea COD_PUB
CREATE TABLE EXISTENCIAS (COD_ARTICULO VARCHAR(50) PRIMARY KEY, NOMBRE VARCHAR(100) NOT NULL DEFAULT 'NoName', CANTIDAD INT NOT NULL DEFAULT '000', 
PRECIO INT NOT NULL CHECK(PRECIO>0) DEFAULT '1', COD_PUB VARCHAR(100), FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB));
-- Crear la tabla PUB_EMPLEADO que usara como llaves foraneas DNI_EMPLEADO y COD_PUB
CREATE TABLE PUB_EMPLEADO (COD_PUB VARCHAR(100), DNI_EMPLEADO VARCHAR(8) DEFAULT '00000000', FUNCION ENUM ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA') NOT NULL, 
PRIMARY KEY(COD_PUB,DNI_EMPLEADO,FUNCION), FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB), FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO));